# Copyright 2014-2017 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

{% set name = "gtk+" %}
{% set version = "3.22.26" %}
{% set version_majmin = '.'.join(version.split('.', 2)[:2]) %}
{% set sha256 = "61eef0d320e541976e2dfe445729f12b5ade53050ee9de6184235cb60cd4b967" %}

package:
  name: gtk3  # note customization
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/{{ name }}/{{ version_majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    - m_pi.patch
    - no-module-warning.patch

build:
  number: 0
  script_env:
    - NJOBS

requirements:
  build:
    - pkg-config
    - pthread-stubs
    - xorg-xproto
    - xorg-inputproto
    - at-spi2-atk 2.25.*
    - atk 2.25.*
    - cairo 1.14.*
    - epoxy 1.4.*
    - fontconfig 2.12.*
    - gdk-pixbuf 2.36.12
    - glib 2.55.*
    - gobject-introspection 1.55.*
    - pango 1.40.*
    - python
    - xorg-libice 1.0.*
    - xorg-libsm 1.2.*
    - xorg-libx11 1.6.*
    - xorg-libxi 1.7.*
    - xorg-libxrender 0.9.*
  run:
    - at-spi2-atk 2.25.*
    - atk 2.25.*
    - cairo 1.14.*
    - epoxy 1.4.*
    - fontconfig 2.12.*
    - gdk-pixbuf 2.36.12
    - glib 2.55.*
    - gobject-introspection 1.55.*
    - pango 1.40.*
    - xorg-libice 1.0.*
    - xorg-libsm 1.2.*
    - xorg-libx11 1.6.*
    - xorg-libxi 1.7.*
    - xorg-libxrender 0.9.*

about:
  home: http://www.gtk.org/
  license: LGPL
  summary: version 3 of the Gtk+ graphical toolkit
